# ROTFLMAO
#
# Das hatte ich original mal eingerichtet, um von Cirrus einen grünen Haken zu bekommen.
#
# Inzwischen hat es sogar einen Sinn mir auf die Griffel zu klopfen,
# wenn ich nachlässigerweise Assets verlinke, die außerhalb des Repos liegen! ;)

container:
  image: busybox:latest

task:
  script: '! grep -r /assets/ *'

