# ROTFLMAO
#
# Wie disablet man Cirrus CI auf einem Repo? ===> Scheint nicht möglich zu sein!
#
# Nun dann, geben wir ihm etwas zu tun.  Eine minimale Busybox erscheint da gerade richtig.
#
# Vielleicht können wir ja mal sogar etwas sinnvolles machen lassen, wie z. B. einen Spellcheck oder eine TOC ..

container:
  image: busybox:latest

task:
  script: grep -r /hilbix/tino/assets/ * 2>/dev/null; test 1 = $?

